Activity check
Swistu/DC-Recomendation-BOT pull request #4
Opened 2022-08-07 14:22 UTC by MaciejGortat

no elo

2022-08-07 14:25 UTC, Swistu commented on bot.js
> +const { updateUser } = require("./database/updateUser");
Importy powinno się dodawać w jakiejś kolejności

2022-08-07 14:38 UTC, Swistu requested changes

2022-08-07 14:38 UTC, Swistu commented on slashcommands/subcommands/user/repair.js
> +    }
Powinien być dodany `else` i informacja zwrotna jeżeli nie udało się ustawić `accountActive `

- [ ] dodać informacje zwrotną na niepowodzenie

2022-08-07 14:55 UTC, Swistu requested changes

2022-08-07 14:55 UTC, Swistu commented on slashcommands/subcommands/user/repair.js
> +  if (userData.payLoad.accountActive == false) {
Zawsze należy korzystać z porównania `===` zamiast `==`

2022-08-08 14:26 UTC, MaciejGortat commented on slashcommands/subcommands/user/repair.js
> +    }
zrobione szefie

2022-08-08 14:33 UTC, Swistu approved these changes
Wszystko git(raczej :D)

2022-08-08 14:34 UTC, merged