Multiple backups
Swistu/DC-Recomendation-BOT pull request #5
Opened 2022-09-06 11:27 UTC by MaciejGortat

hello my friend
please accept my pull request
best regards

2022-09-06 17:36 UTC, Swistu requested changes
No ogólnie trochę poprawek rozdzielenie operacji na bazie, z tym co sama aplikacja robi.
Taki mały error krytyczny się wdarł, że cała apka nie działa.
No i przekleństwa bezsensu. Można easter eggi ale jak będą ze smakiem.

2022-09-06 17:36 UTC, Swistu commented on bot.js
> -  if (process.env.NODE_ENV !== "development") {
Powinieneś zostawić wyłączenie backup'ów na dev, co by móc korzystać z nodemon i nie zaśmiecać sobie dysku

2022-09-06 17:36 UTC, Swistu commented on bot.js
> +  console.log(message.message);
Ten consol log nic nie mówi, zostanie pokazany tylko i wyłącznie na serwerze, a tam nas tylko interesują errory w razie co.

2022-09-06 17:36 UTC, Swistu commented on bot.js
> +    createJSONFile
Ta linijka wali error jeżeli chcemy w jakikolwiek inny sposób niż backup korzystać z bota

2022-09-06 17:36 UTC, Swistu commented on database/doBackup.js
> +        const session = client.startSession();
Zmienna sesja nie jest tutaj kompletnie potrzebna

2022-09-06 17:36 UTC, Swistu commented on database/doBackup.js
> +const { sendFile } = require("../utility/sendFile");
Cały folder database służy tylko do operacji na bazie zapis/odczyt/update itp. Ty dajesz tutaj logikę aplikacji.

Powinieneś zrobić tak, żeby ta funkcja zwróciła Tobie to co potrzebujesz czyli, listę kolekcji wraz z danymi, a samo wysyłanie wiadomości zrobić w innym miejscu. Dla przykładu w tym bot.js gdzie teraz wywołujesz całą funkcje doBackup

2022-09-06 17:36 UTC, Swistu commented on database/doBackup.js
> +        await channel.send("Backupujemy tutaj! Jest dobrze w chuj!");
Żaden easter egg tylko zwykłe wysyłanie można by do zamienić na jakiś format typu backup dzień: day-month-year
czy coś takiego, ogólnie bez przekleństw w kodzie gdyby można.

2022-09-06 17:36 UTC, Swistu commented on database/doBackup.js
> +    return { valid: true, message: "Backupujemy tutaj! Jest dobrze w chuj!" };
Tu też przekleństwa

2022-09-06 17:36 UTC, Swistu commented on utility/sendFile.js
> +  const client = bot;
Po co tworzyć druga identyczną zmienna?

wykorzystaj już to co przyjmujesz w parametrach funkcji `bot` jak chcesz tego nazwę mieć jako client to zamień po prostu `bot` na `client`

2022-09-06 17:36 UTC, Swistu commented on utility/createJSONFile.js
> +    const result = fs.writeFile(fileName, data, (error) => {
Nie wykorzystujesz zmiennej error.

Jeżeli zaraz po wywołaniu zmiennej ją zwracasz to wypadałoby to skrócić do jednej linijki po co bez sensu zapisywać jakąś zmienną.

```
 const result = cos;
 return result;
```
```
 return cos;
```

2022-09-06 17:57 UTC, MaciejGortat commented on database/doBackup.js
> +        const session = client.startSession();
a jak potem zamkne sesje?

2022-09-06 17:58 UTC, MaciejGortat commented on bot.js
> +  console.log(message.message);
dobra, usunie sie

2022-09-06 17:58 UTC, MaciejGortat commented on bot.js
> -  if (process.env.NODE_ENV !== "development") {
oh crap

2022-09-06 17:59 UTC, MaciejGortat commented on database/doBackup.js
> +const { sendFile } = require("../utility/sendFile");
oke nie bij

2022-09-06 17:59 UTC, MaciejGortat commented on database/doBackup.js
> +        await channel.send("Backupujemy tutaj! Jest dobrze w chuj!");
ok boomer

2022-09-06 17:59 UTC, MaciejGortat commented on database/doBackup.js
> +    return { valid: true, message: "Backupujemy tutaj! Jest dobrze w chuj!" };
ok boomer

2022-09-06 18:01 UTC, MaciejGortat commented on utility/sendFile.js
> +  const client = bot;
a widzisz, wzialem to z twojego kodu - slashcommands.js linijka 8

2022-09-06 18:03 UTC, MaciejGortat commented on utility/createJSONFile.js
> +    const result = fs.writeFile(fileName, data, (error) => {
error usune, ale chyba byl jakis powod z tym constem, sprawdze

2022-09-06 18:06 UTC, Swistu commented on database/doBackup.js
> +        const session = client.startSession();
nie korzystaj w ogóle z sesji

2022-09-06 18:07 UTC, Swistu commented on utility/sendFile.js
> +  const client = bot;
jest różnica między `const { client } = bot;`  a ``const client = bot;`

2022-09-18 17:42 UTC, Swistu requested changes
Do poprawki małej

2022-09-18 17:42 UTC, Swistu commented on utility/doBackup.js
> +    const collections = (await getAllData()).payload;
Nie sprawdzasz czy z bazy masz prawidłową odpowiedź

2022-09-18 18:10 UTC, Swistu approved these changes
Wszystko ok

2022-09-18 18:18 UTC, merged